FROM mysql:8

# 환경 변수를 설정하여 MySQL 데이터베이스를 초기화합니다.
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=reactive_study
# ENV MYSQL_USER=root
# ENV MYSQL_PASSWORD=root

# 데이터베이스 초기화 스크립트를 복사합니다.
COPY init.sql /docker-entrypoint-initdb.d/

# 포트를 열어 외부에서 접근할 수 있도록 설정합니다.
EXPOSE 3306